### ISSUE TITLE
Error after some Time

### ISSUE THREAD

**Issue by mrcsdl** [gottagofaster236/Twitch-Channel-Points-Miner#14]
Hey today i got an error maybe its on my site, but maybe its an bug. I Just wanted to report it in case.

Thats the message:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/opt/python-3.7.0/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/opt/python-3.7.0/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/twitch/pubsub.py", line 52, in run
    ping(ws)
  File "/home/pi/twitch/pubsub.py", line 118, in ping
    send(ws, {"type": "PING"})
  File "/home/pi/twitch/pubsub.py", line 123, in send
    ws.send(request_str)
  File "/home/pi/.local/lib/python3.7/site-packages/websocket/_app.py", line 156, in send
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.

^CException ignored in: <module 'threading' from '/usr/local/opt/python-3.7.0/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/local/opt/python-3.7.0/lib/python3.7/threading.py", line 1273, in _shutdown
    t.join()
  File "/usr/local/opt/python-3.7.0/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/local/opt/python-3.7.0/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):

**Comment by gottagofaster236** [comment]
Yeah, thanks, probably will have to implement reconnecting to PubSub properly

**Comment by gottagofaster236** [comment]
Should be fixed in beace3b3f4672446654e873297b216c28ff119da.
